### ISSUE TITLE
PHP 7.2 issue - Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tyler-deboer** [supercool/buttonbox#18]
I'm getting a PHP error any time I try saving an entry with a Button Box field. 

```count(): Parameter must be an array or an object that implements Countable```

The error says it's happening on Line 226 of `vendor/craftcms/cms/src/fields/BaseOptionsField`. Since the error is happening in the Craft vendor package, it may be something that has to be fixed in Craft itself? Or is that something that can be addressed in the plugin?

Interestingly enough, when I switched my MAMP environment from PHP 7.2 to PHP 7.1, the problem went away and I was able to save things correctly. So it seems to be a 7.2-specific issue.

PHP Version: 7.2.1
Craft Version: Craft Solo 3.0.3.1
Button Box Version: 2.0.0

**Comment by E2design** [comment]
Same issue here while using button box in a matrix or NEO field.

`count(): Parameter must be an array or an object that implements Countable`

PHP 7.2.1
Craft Pro 3.0.9
Button box 2.0.0

**Comment by Nav33d** [comment]
@tyler-deboer @E2design I have just tested this using PHP 7.2.6 and Craft 3.0.9 and it all worked fine regardless of whether it is inside a Matrix or on its own.

Could you please confirm if you are still getting the error?

**Comment by E2design** [comment]
Issue still persists

**Comment by Nav33d** [comment]
@chasegiunta @E2design I have released a new version of the plugin which should fix this issue.

**Comment by jeffaglenn** [comment]
Still having this issue. Any thoughts?
Craft CMS 3.0.15
PHP 7.2.1
Button Box 2.0.1

**Comment by jeffaglenn** [comment]
Looks like the updates made to `Colours.php` need to be made to `Buttons.php` as well.

**Comment by E2design** [comment]
Still having the issues

PHP 7.2.7
Craft 3.0.15
Button box 2.01

![schermafdruk 2018-07-11 10 36 15](https://user-images.githubusercontent.com/5907530/42560265-8b3946b2-84f6-11e8-8293-fc15fa632640.png)

**Comment by Nav33d** [comment]
@jeffaglenn @E2design Thank you for reporting this. I have fixed count error for Buttons, Text Size and Width field types. Please downloaded the latest version 2.0.2 :)
